# .sops.yaml
keys:
  - &admin_key age1g4qqkd4l55kl2q8x85d78dm84fgazv5nns6n3fw7zw6lp8m9k9wsc6w70d

creation_rules:
  # 1. Matches any yaml file inside a 'secrets' folder
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin_key

  # 2. Matches any 'secrets.yaml' file inside any subfolder
  - path_regex: .*/secrets\.yaml$
    key_groups:
      - age:
          - *admin_key
