[env]
USER = "radio" # TODO This value is set here and in flake.nix
SSH_PORT = "22" # TODO This value is set here and in flake.nix

HETZNER_SERVER_NAME = "radio-pepper"
# _.source = { path = "./mise-tasks/load_secrets", tools = true }


[tools]
age = "latest"
hcloud = "latest"
pre-commit = "latest"
sops = "latest"

#[shell_alias]
#dev-ssh = "mise r dev-ssh"
#prod-ssh = "mise r prod-ssh"

[tasks.vm-start]
description = "Start the local development vm at localhost:8080"
run = '''
    # 🚀 Starting local VM...
    echo "This will start a NixOS VM with your configuration"
    echo "The VM will be accessible at: http://localhost:8080"
    echo ""

    mkdir -p "$MISE_PROJECT_ROOT/.state/vm"
    export NIX_DISK_IMAGE="$MISE_PROJECT_ROOT/.state/vm/local.qcow2"

    "$MISE_PROJECT_ROOT/build/vm/bin/run-pepper-vm"
'''

[tasks.vm-build]
description = "Build a local qemu vm to ./build/vm"
run = '''
    # Building VM...

    nix build "$MISE_PROJECT_ROOT#nixosConfigurations.dev-local.config.system.build.vm" \
        -o "$MISE_PROJECT_ROOT/build/vm"
    echo "✅ VM built! Run 'mise r vm-start' to launch it"
'''

[tasks.dev-ssh]
description = "Connect to local VM on port 2222"
run = '''
    # Connect SSH on port 2222...

    echo "waiting for local VM to accept connections..."
    until nc -z localhost 2222; do sleep 1; done

    KEY_PATH=$(mktemp)
    trap 'rm -f "$KEY_PATH"' EXIT
    chmod 600 "$KEY_PATH"
    cat ./secrets/dev/ssh_host_ed25519_key > "$KEY_PATH"
    # fnox get LOCAL_SSH > "$KEY_PATH" # for mental reference if needed

    ssh -i ./secrets/dev/ssh_host_ed25519_key \
        -o IdentitiesOnly=yes \
        -o UserKnownHostsFile=/dev/null \
        -o StrictHostKeyChecking=no \
        $USER@localhost -p 2222
'''

[tasks.prod-ssh]
description = "Connect to remote VM"
run = '''
    # Connect SSH on port $SSH_PORT...

    export HCLOUD_TOKEN=$(sops -d --extract '["hetzner_api_token"]' "./secrets/prod.enc.yaml")
    # Check if the variable is empty
    if [ -z "$HCLOUD_TOKEN" ]; then
        echo "❌ Error: HCLOUD_TOKEN is not set."
        echo "💡 Hint: Ensure you can access prod.enc.yaml for the token."
        exit 1
    fi

    echo "waiting for remote VM to accept connections..."
    REMOTE_IP4=$(hcloud server ip "$HETZNER_SERVER_NAME")
    until nc -z $REMOTE_IP4 $SSH_PORT; do sleep 1; done

    KEY_PATH=$(mktemp)
    trap 'rm -f "$KEY_PATH"' EXIT
    chmod 600 "$KEY_PATH"
    sops -d --extract '["id_ed25519"]' "$MISE_PROJECT_ROOT/secrets/prod.enc.yaml" \
        > "$KEY_PATH"
    ssh -i "$KEY_PATH" \
        -o IdentitiesOnly=yes \
        $USER@$REMOTE_IP4 -p $SSH_PORT
'''

[hooks]
enter = '''
    echo "🌥️  Radio Pepper"
    echo ""
    echo "Available commands:"
    mise tasks
    echo ""
    echo "Run them with 'mise r name'"
    echo ""
'''
