[project]
name = "radio-pepper"
revision = "1.0"

[profiles.default]
SSH_KEY = { description = "SSH Key for VM/Remote", required = true, as_path = true }
SSH_PUB = { description = "SSH Public for VM/Remote", required = true }

[profiles.development]
SSH_KEY = { description = "The local private key for ssh-ing into the vm" }
SSH_PUB = { description = "The local public key baked into the image" }

[profiles.production]
SSH_KEY = { description = "The remote private key for ssh-ing into the vm" }
SSH_PUB = { description = "The remote public key baked into the image" }
