#!/usr/bin/env bash

export HCLOUD_TOKEN=$(sops -d --extract '["hetzner_api_token"]' "./secrets/hcloud.enc.yaml")
export DEV_SSH_KEY=$(sops -d --extract '["development_ssh_key"]' "./secrets/ssh_private_keys.enc.yaml")
export PROD_SSH_KEY=$(sops -d --extract '["production_ssh_key"]' "./secrets/ssh_private_keys.enc.yaml")
